### ISSUE TITLE
Make ingress path configurable

### ISSUE THREAD

**Issue by smarch730** [atlassian-labs/data-center-helm-charts#129]
Currently the ingress path for all applications is set to "/". Can this be changed to be a configurable value?

```
 rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: "/"    =>    {{ $.Values.ingress.path }}
            backend:
              serviceName: {{ include "jira.fullname" $ }}
              servicePort: {{ $.Values.jira.service.port }}
```
