### ISSUE TITLE
Driver for the database MySQL 5.7 not found

### ISSUE THREAD

**Issue by Forbzy** [atlassian-labs/data-center-helm-charts#239]
It appears my database configuration isn't be acknowledged. 

Below is my error log.

`2021-08-14 13:12:04,624+0000 JIRA-Bootstrap FATAL      [c.a.jira.startup.JiraStartupLogger] Driver for the database MySQL 5.7 not found. Ensure it is installed in the 'lib' directory.`

Below is the values.yaml for the database.

```
database:
      type: mysql8
      url: jdbc:mysql://mysql/my_database
      driver: com.mysql.jdbc.Driver
      credentials:
        secretName: mysql-creds
        usernameSecretKey: username
        passwordSecretKey: password
```

How to reproduce.
1. Helm install

**Comment by errcode1202** [comment]
@Forbzy I think this is a failure on our documentation. There is a [section relating to DB drivers](https://atlassian-labs.github.io/data-center-helm-charts/userguide/CONFIGURATION/#databasedriver), but it not overly clear that the `MySQL` drivers don't ship with Jira, and must be supplied manually. There are details on where the driver `MySQL` driver can be sourced [here.](https://confluence.atlassian.com/adminjiraserver/connecting-jira-applications-to-mysql-8-0-1018775461.html#ConnectingJiraapplicationstoMySQL8.0-driver) This driver can then be mounted as an `additionalLibraries` using the instructions [here](https://atlassian-labs.github.io/data-center-helm-charts/userguide/CONFIGURATION/#additional-libraries-plugins)

**Comment by errcode1202** [comment]
@Forbzy this is a failure on our documentation's part. Jira doesn't actually ship with the `MySQL` driver and needs to be supplied manually. We do allude to this in the [docs](https://atlassian-labs.github.io/data-center-helm-charts/userguide/CONFIGURATION/#databasedriver) but its easily missed, something that we'll look into addressing. As for getting you up and running, the way to present the driver to each of your Pod's is to first [download](https://confluence.atlassian.com/adminjiraserver/connecting-jira-applications-to-mysql-8-0-1018775461.html#ConnectingJiraapplicationstoMySQL8.0-driver) the driver and add it to a sub-dir (e.g. `drivers`) of your [shared-home](https://atlassian-labs.github.io/data-center-helm-charts/userguide/PREREQUISITES/#configure-a-shared-home-volume) volume. You can then define the additional library (driver) under `additionalLibraries`.

```yaml
jira:
 additionalLibraries: 
  - volumeName: shared-home
    subDirectory: drivers
    fileName: mysql-driver.jar
```
