### ISSUE TITLE
Additional variables do not seem to work properly

### ISSUE THREAD

**Issue by bordenit** [atlassian-labs/data-center-helm-charts#85]
Here is an example configmap that does work....
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-config
  labels:
    app: jira
data:
  JVM_MINIMUM_MEMORY: 2048m
  JVM_MAXIMUM_MEMORY: 4096m
  ATL_JDBC_USER: "{{ jiradbUsername }}"
  ATL_JDBC_PASSWORD: "{{ jiradbPassword }}"
  ATL_DB_DRIVER: org.postgresql.Driver
  ATL_JDBC_URL: jdbc:postgresql://postgres-jira:5432/jiradb
  CLUSTERED: "true"
  ATL_DB_TYPE: postgres72
  JIRA_SHARED_HOME: /var/atlassian/application-data/jira/shared
```

I tried adding ATL_TOMCAT_CONTEXTPATH variable using the helm chart and I think it maybe puts it in the wrong place. You could possibly group all the container variable options under data in configmap like the above.
